baseURL = 'https://climbing.uwaterloo.ca/'
languageCode = 'en-us'
title = 'UW Climbing Club'
theme = 'paper'
paginate = 4
enableEmoji = true


[params]
  color = 'light'
  monoDarkIcon = true

  instagram = 'wlooclimbingclub'
  discord = 'BZzNzNq5Up'
  membership_link = 'https://warrior.uwaterloo.ca/membership/GetMembershipSummary?membershipProductId=dc3ed568-3fae-41d2-aa32-e4bc5be6dd85'

  name = 'Welcome! ðŸ‘‹'
  bio = "We're the University of Waterloo Climbing Club. Below you can find updates on our events and other club activities. We also post regularly on our Discord and Instragram. If you're interested in joining, check out our membership page!"

  logo = 'logo.svg'
  logo2 = 'climber.svg'


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 3

  [[menu.main]]
    identifier = 'membership'
    name = 'Membership'
    url = '/membership/'
    weight = 4 


[markup.goldmark.renderer]
  unsafe = true
